version: "3"

services:
  redis:
    image: redis
    volumes:
      - ./redis/data:/data
    restart: always
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./.bashrc:/root/.bashrc
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
