# Generated by Django 4.1.2 on 2022-11-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dragdrop2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="convert",
            name="editFlg",
            field=models.BooleanField(default=False),
        ),
    ]
